# Generated by Django 4.1.2 on 2022-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_alter_flexpage_options_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Quaerat consectetur dolor aliquam numquam neque. Modi porro voluptatem labore est. Numquam modi quiquia adipisci voluptatem etincidunt quiquia. Ut quisquam eius dolorem labore amet consectetur. Porro sed magnam sit. Modi porro ut tempora neque. Ipsum consectetur magnam quisquam sed neque etincidunt voluptatem.', max_length=600, null=True),
        ),
    ]
