# Generated by Django 4.1.2 on 2022-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Dolorem sit ipsum numquam neque amet neque dolorem. Sit est porro aliquam porro dolore ut adipisci. Quiquia quisquam est quaerat modi. Quiquia quisquam quiquia porro aliquam sit ipsum. Etincidunt eius adipisci non. Neque tempora consectetur etincidunt numquam dolorem etincidunt. Dolore labore ipsum eius. Numquam magnam dolorem neque aliquam. Dolorem porro modi voluptatem adipisci dolore numquam. Numquam magnam consectetur est voluptatem ipsum magnam eius.', max_length=600, null=True),
        ),
    ]
