# Generated by Django 4.1.2 on 2022-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Consectetur aliquam numquam tempora amet magnam. Non quiquia sed tempora. Velit non tempora est. Numquam porro aliquam porro sit dolor tempora aliquam. Dolor etincidunt ut ut labore. Aliquam tempora eius adipisci eius.', max_length=600, null=True),
        ),
    ]
