# Generated by Django 4.1.2 on 2022-10-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Aliquam numquam amet quiquia numquam eius etincidunt numquam. Velit dolore quaerat voluptatem modi est. Neque eius consectetur ut dolorem dolor porro amet. Est ut neque voluptatem velit labore dolore quaerat. Est amet magnam non non.', max_length=600, null=True),
        ),
    ]
